### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by zach721** [codeooze/react-native-wallpaper-manager#1]
Uncaught Error: The package '@codeooze/react-native-wallpaper-manager' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo managed workflow

I used "npx react-native link " and it doesn't works

**Comment by codeooze** [comment]
> Uncaught Error: The package '@codeooze/react-native-wallpaper-manager' doesn't seem to be linked. Make sure:
> 
>     * You rebuilt the app after installing the package
> 
>     * You are not using Expo managed workflow
> 
> 
> I used "npx react-native link " and it doesn't works

Fixed and updated a new version :)
